name: Containers CI

on:
  workflow_run:
    workflows: [Build and Tests]
    types:
      - completed
  release:
    types: [created]

jobs:
  build_cache_buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup disk
        run: |
          sudo ls -l /usr/local/lib/
          sudo ls -l /usr/share/
          sudo du -sh /usr/local/lib/
          sudo du -sh /usr/share/
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo du -sh /usr/local/lib/
          sudo du -sh /usr/share/

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v4
        with:
          context: ./
          file: .devcontainer/Containerfile
          push: false

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: python-dev
          tags: latest ${{ github.sha }}
          containerfiles: |
            .devcontainer/Containerfile
